[package]
name = "groove-gunner"
version = "0.1.0"
edition = "2021"

[dependencies]
tiled-json-rs = "0.2.6"

[dependencies.raylib]
version = "5.0.0"
git = "https://github.com/bitten2up/raylib-rs"
branch = "5.0.0"
